name: Healthcheck

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:       # allow manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping carolinesalib.com
        run: curl -f https://carolinesalib.com/up
